### ISSUE TITLE
Chat Room: start implementing Andy’s room lifecycle spec

### ISSUE THREAD

**Issue by jamienewcomb** [ably-labs/ably-chat-swift#28]
Implement https://github.com/ably/specification/pull/200/. https://ably.atlassian.net/wiki/spaces/CHA/pages/3156705308/CHADR-038+API+Design+Separating+Listeners+from+Lifecycle apparently gives some background on the motivation for the complexity of this spec.

I mistakenly started implementing this when working on https://github.com/ably-labs/ably-chat-swift/issues/19; my WIP is https://github.com/ably-labs/ably-chat-swift/pull/30.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4952) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
Initial chunk of implementation is in #54, and I’ve broken the remaining work into multiple issues.

**Comment by lawrence-forooghian** [comment]
Resolved by #54.
